exclude: '^$'
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.285
  hooks:
    - id: ruff
      # args: [--fix, --exit-non-zero-on-fix]
      args: [--fix]